"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataTypes__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "x",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "interAxisX",
                type: "uint256",
            },
        ],
        name: "InvalidAxisX",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "x",
                type: "uint256",
            },
        ],
        name: "InvalidAxisY",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "interAxisX",
                type: "uint256",
            },
        ],
        name: "InvalidIntersectionAxisX",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "interAxisX",
                type: "uint256",
            },
        ],
        name: "InvalidIntersectionAxisY",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "T",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "E",
                type: "uint256",
            },
        ],
        name: "InvalidTE",
        type: "error",
    },
];
var _bytecode = "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ddf3bc868854584c3a6b9c8f8ed645905685c8418e6128e77bb07d77ce448f1e64736f6c63430008090033";
var DataTypes__factory = /** @class */ (function (_super) {
    __extends(DataTypes__factory, _super);
    function DataTypes__factory() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        var _this = this;
        if (args.length === 1) {
            _this = _super.call(this, _abi, _bytecode, args[0]) || this;
        }
        else {
            _this = _super.apply(this, args) || this;
        }
        return _this;
    }
    DataTypes__factory.prototype.deploy = function (overrides) {
        return _super.prototype.deploy.call(this, overrides || {});
    };
    DataTypes__factory.prototype.getDeployTransaction = function (overrides) {
        return _super.prototype.getDeployTransaction.call(this, overrides || {});
    };
    DataTypes__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    DataTypes__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    DataTypes__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    DataTypes__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    DataTypes__factory.bytecode = _bytecode;
    DataTypes__factory.abi = _abi;
    return DataTypes__factory;
}(ethers_1.ContractFactory));
exports.DataTypes__factory = DataTypes__factory;
