/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { DataTypes, DataTypesInterface } from "../DataTypes";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "interAxisX",
        type: "uint256",
      },
    ],
    name: "InvalidAxisX",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
    ],
    name: "InvalidAxisY",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "interAxisX",
        type: "uint256",
      },
    ],
    name: "InvalidIntersectionAxisX",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "interAxisX",
        type: "uint256",
      },
    ],
    name: "InvalidIntersectionAxisY",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "T",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "E",
        type: "uint256",
      },
    ],
    name: "InvalidTE",
    type: "error",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c745efd507fcb5551854e889fc067119caa0b5e567a8e172de9cd6eb966d463164736f6c63430008090033";

export class DataTypes__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DataTypes> {
    return super.deploy(overrides || {}) as Promise<DataTypes>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DataTypes {
    return super.attach(address) as DataTypes;
  }
  connect(signer: Signer): DataTypes__factory {
    return super.connect(signer) as DataTypes__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DataTypesInterface {
    return new utils.Interface(_abi) as DataTypesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DataTypes {
    return new Contract(address, _abi, signerOrProvider) as DataTypes;
  }
}
